#!/usr/bin/env python3
"""Terminal login/signup app generated by Conductor."""

from __future__ import annotations

import argparse
import getpass
import hashlib
import hmac
import os
import secrets
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import List, Optional


ITERATIONS = 260_000
DEFAULT_ADMIN_USER = "admin"
DEFAULT_ADMIN_PASSWORD = "admin123"


HELP_TEXT = """
Commands
  help                 Show this help
  settings             View your settings
  set KEY VALUE        Change one of your settings
  password             Change your password
  admin                Open admin menu if you are an admin
  logout               Sign out
  exit                 Exit the app
""".strip()


ADMIN_HELP_TEXT = """
Admin commands
  list                 Show all users
  edit USERNAME        Rename a user or change admin flag
  reset USERNAME       Reset a user's password
  delete USERNAME      Delete a user
  settings USERNAME    Edit another user's settings
  back                 Return to user menu
  help                 Show this help
""".strip()


def connect(db_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def init_db(conn: sqlite3.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            is_admin INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS settings (
            user_id INTEGER NOT NULL,
            key TEXT NOT NULL,
            value TEXT NOT NULL,
            PRIMARY KEY (user_id, key),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    conn.commit()


def hash_password(password: str, salt: Optional[bytes] = None) -> str:
    if salt is None:
        salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, ITERATIONS)
    return f"pbkdf2_sha256${ITERATIONS}${salt.hex()}${digest.hex()}"


def verify_password(password: str, stored_hash: str) -> bool:
    try:
        scheme, iterations, salt_hex, digest_hex = stored_hash.split("$", 3)
        if scheme != "pbkdf2_sha256":
            return False
        candidate = hashlib.pbkdf2_hmac(
            "sha256",
            password.encode("utf-8"),
            bytes.fromhex(salt_hex),
            int(iterations),
        ).hex()
        return hmac.compare_digest(candidate, digest_hex)
    except (ValueError, TypeError):
        return False


def bootstrap_admin(conn: sqlite3.Connection) -> None:
    row = conn.execute("SELECT COUNT(*) AS count FROM users WHERE is_admin = 1").fetchone()
    if row["count"] == 0:
        create_user(conn, DEFAULT_ADMIN_USER, DEFAULT_ADMIN_PASSWORD, is_admin=True)
        print(f"Default admin created: {DEFAULT_ADMIN_USER} / {DEFAULT_ADMIN_PASSWORD}")


def create_user(conn: sqlite3.Connection, username: str, password: str, is_admin: bool = False) -> int:
    username = username.strip()
    if not username:
        raise ValueError("Username cannot be empty.")
    if len(password) < 6:
        raise ValueError("Password must be at least 6 characters.")
    cur = conn.execute(
        "INSERT INTO users (username, password_hash, is_admin) VALUES (?, ?, ?)",
        (username, hash_password(password), int(is_admin)),
    )
    conn.commit()
    set_setting(conn, cur.lastrowid, "theme", "default")
    set_setting(conn, cur.lastrowid, "notifications", "on")
    return int(cur.lastrowid)


def authenticate(conn: sqlite3.Connection, username: str, password: str) -> Optional[sqlite3.Row]:
    row = conn.execute("SELECT * FROM users WHERE username = ?", (username.strip(),)).fetchone()
    if row is None:
        return None
    if verify_password(password, row["password_hash"]):
        return row
    return None


def user_by_username(conn: sqlite3.Connection, username: str) -> Optional[sqlite3.Row]:
    return conn.execute("SELECT * FROM users WHERE username = ?", (username.strip(),)).fetchone()


def set_setting(conn: sqlite3.Connection, user_id: int, key: str, value: str) -> None:
    conn.execute(
        """
        INSERT INTO settings (user_id, key, value)
        VALUES (?, ?, ?)
        ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
        """,
        (user_id, key.strip(), value.strip()),
    )
    conn.commit()


def settings_for(conn: sqlite3.Connection, user_id: int) -> List[sqlite3.Row]:
    return list(conn.execute("SELECT key, value FROM settings WHERE user_id = ? ORDER BY key", (user_id,)))


def print_table(headers: List[str], rows: List[List[str]]) -> None:
    widths = [len(h) for h in headers]
    for row in rows:
        for idx, cell in enumerate(row):
            widths[idx] = max(widths[idx], len(str(cell)))
    line = "+".join("-" * (w + 2) for w in widths)
    print(line)
    print("|".join(f" {headers[idx]:<{widths[idx]}} " for idx in range(len(headers))))
    print(line)
    for row in rows:
        print("|".join(f" {str(row[idx]):<{widths[idx]}} " for idx in range(len(headers))))
    print(line)


def list_users(conn: sqlite3.Connection) -> None:
    rows = [
        [str(row["id"]), row["username"], "yes" if row["is_admin"] else "no", row["created_at"]]
        for row in conn.execute("SELECT id, username, is_admin, created_at FROM users ORDER BY id")
    ]
    print_table(["id", "username", "admin", "created"], rows)


def prompt_password(confirm: bool = False) -> str:
    password = getpass.getpass("Password: ")
    if confirm:
        again = getpass.getpass("Confirm password: ")
        if password != again:
            raise ValueError("Passwords do not match.")
    return password


def signup(conn: sqlite3.Connection) -> None:
    username = input("Choose username: ").strip()
    try:
        create_user(conn, username, prompt_password(confirm=True))
        print("Account created. You can log in now.")
    except sqlite3.IntegrityError:
        print("That username already exists.")
    except ValueError as exc:
        print(exc)


def login(conn: sqlite3.Connection) -> Optional[sqlite3.Row]:
    username = input("Username: ").strip()
    password = getpass.getpass("Password: ")
    user = authenticate(conn, username, password)
    if user is None:
        print("Invalid username or password.")
        return None
    print(f"Welcome, {user['username']}.")
    return user


def change_password(conn: sqlite3.Connection, user: sqlite3.Row) -> None:
    current = getpass.getpass("Current password: ")
    if not verify_password(current, user["password_hash"]):
        print("Current password is incorrect.")
        return
    try:
        new_password = prompt_password(confirm=True)
    except ValueError as exc:
        print(exc)
        return
    conn.execute("UPDATE users SET password_hash = ? WHERE id = ?", (hash_password(new_password), user["id"]))
    conn.commit()
    print("Password changed.")


def edit_settings(conn: sqlite3.Connection, user_id: int) -> None:
    while True:
        rows = settings_for(conn, user_id)
        if rows:
            print_table(["key", "value"], [[row["key"], row["value"]] for row in rows])
        else:
            print("No settings yet.")
        command = input("settings> ").strip()
        if command in {"back", "exit", "logout"}:
            return
        if command == "help":
            print("Use: set KEY VALUE, or back")
            continue
        if command.startswith("set "):
            _, rest = command.split(" ", 1)
            parts = rest.split(" ", 1)
            if len(parts) != 2:
                print("Use: set KEY VALUE")
                continue
            set_setting(conn, user_id, parts[0], parts[1])
            print("Setting saved.")
            continue
        print("Unknown settings command.")


def admin_menu(conn: sqlite3.Connection, current_user: sqlite3.Row) -> None:
    if not current_user["is_admin"]:
        print("Admin access required.")
        return
    print(ADMIN_HELP_TEXT)
    while True:
        command = input("admin> ").strip()
        if command in {"back", "exit", "logout"}:
            return
        if command == "help":
            print(ADMIN_HELP_TEXT)
            continue
        if command == "list":
            list_users(conn)
            continue
        if command.startswith("delete "):
            target_name = command.split(" ", 1)[1].strip()
            target = user_by_username(conn, target_name)
            if target is None:
                print("User not found.")
                continue
            if target["id"] == current_user["id"]:
                print("You cannot delete your own account while signed in.")
                continue
            conn.execute("DELETE FROM users WHERE id = ?", (target["id"],))
            conn.commit()
            print("User deleted.")
            continue
        if command.startswith("reset "):
            target = user_by_username(conn, command.split(" ", 1)[1])
            if target is None:
                print("User not found.")
                continue
            try:
                new_password = prompt_password(confirm=True)
            except ValueError as exc:
                print(exc)
                continue
            conn.execute("UPDATE users SET password_hash = ? WHERE id = ?", (hash_password(new_password), target["id"]))
            conn.commit()
            print("Password reset.")
            continue
        if command.startswith("settings "):
            target = user_by_username(conn, command.split(" ", 1)[1])
            if target is None:
                print("User not found.")
                continue
            edit_settings(conn, target["id"])
            continue
        if command.startswith("edit "):
            target = user_by_username(conn, command.split(" ", 1)[1])
            if target is None:
                print("User not found.")
                continue
            new_name = input(f"New username [{target['username']}]: ").strip() or target["username"]
            admin_raw = input(f"Admin yes/no [{'yes' if target['is_admin'] else 'no'}]: ").strip().lower()
            new_admin = target["is_admin"]
            if admin_raw in {"yes", "y"}:
                new_admin = 1
            elif admin_raw in {"no", "n"}:
                new_admin = 0
            try:
                conn.execute(
                    "UPDATE users SET username = ?, is_admin = ? WHERE id = ?",
                    (new_name, int(new_admin), target["id"]),
                )
                conn.commit()
                print("User updated.")
            except sqlite3.IntegrityError:
                print("That username already exists.")
            continue
        print("Unknown admin command.")


def user_menu(conn: sqlite3.Connection, user: sqlite3.Row) -> None:
    print(HELP_TEXT)
    while True:
        refreshed = conn.execute("SELECT * FROM users WHERE id = ?", (user["id"],)).fetchone()
        if refreshed is None:
            print("Your account no longer exists.")
            return
        user = refreshed
        command = input(f"{user['username']}> ").strip()
        if command in {"logout", "exit"}:
            return
        if command == "help":
            print(HELP_TEXT)
            continue
        if command == "settings":
            edit_settings(conn, user["id"])
            continue
        if command.startswith("set "):
            parts = command.split(" ", 2)
            if len(parts) != 3:
                print("Use: set KEY VALUE")
                continue
            set_setting(conn, user["id"], parts[1], parts[2])
            print("Setting saved.")
            continue
        if command == "password":
            change_password(conn, user)
            continue
        if command == "admin":
            admin_menu(conn, user)
            continue
        print("Unknown command. Type help.")


def run_shell(db_path: Path) -> None:
    conn = connect(db_path)
    init_db(conn)
    bootstrap_admin(conn)
    print("Login / signup terminal app")
    print("Type help from any menu for commands.")
    while True:
        command = input("main> ").strip().lower()
        if command in {"exit", "quit"}:
            return
        if command == "help":
            print("Commands: login, signup, help, exit")
            continue
        if command == "signup":
            signup(conn)
            continue
        if command == "login":
            user = login(conn)
            if user is not None:
                user_menu(conn, user)
            continue
        print("Unknown command. Try login, signup, help, or exit.")


def self_test() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        db_path = Path(tmp) / "users.db"
        conn = connect(db_path)
        init_db(conn)
        admin_id = create_user(conn, "admin", "admin123", is_admin=True)
        user_id = create_user(conn, "max", "secret123")
        row = authenticate(conn, "max", "secret123")
        assert row is not None
        assert authenticate(conn, "max", "wrong") is None
        stored = conn.execute("SELECT password_hash FROM users WHERE username = 'max'").fetchone()["password_hash"]
        assert "secret123" not in stored
        assert stored.startswith("pbkdf2_sha256$")
        set_setting(conn, user_id, "theme", "dark")
        assert any(item["value"] == "dark" for item in settings_for(conn, user_id))
        conn.execute("UPDATE users SET is_admin = 1 WHERE id = ?", (user_id,))
        conn.commit()
        assert conn.execute("SELECT is_admin FROM users WHERE id = ?", (user_id,)).fetchone()["is_admin"] == 1
        assert admin_id > 0
    print("SELF_TEST_OK")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Terminal login/signup app")
    parser.add_argument("--db", default=str(Path(__file__).with_name("users.db")), help="SQLite database path")
    parser.add_argument("--self-test", action="store_true", help="Run non-interactive checks")
    args = parser.parse_args(argv)
    if args.self_test:
        self_test()
        return 0
    run_shell(Path(args.db))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
